### ISSUE TITLE
Exception when test with real web page html

### ISSUE THREAD

**Issue by m00nlight** [devn/yokogiri#5]
When I use `yokogiri` to parse real webpages using the following code.

``` clojure
(defn extract-one-page
  "fname is file name for the baike document."
  [fname]
  (let [doc ($/as-page fname)]
    (println doc)
    ))
```

It raise exceptions as follow:

``` clojure
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[The data necessary to complete this operation is not yet available.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[1] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[An invalid or illegal selector was specified (selector: ':checked' error: Invalid selector: *:checked).] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[An invalid or illegal selector was specified (selector: ':enabled' error: Invalid selector: *:enabled).] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.12'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.12'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.11'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.11'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.10'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.10'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.9'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.9'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.8'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.8'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.7'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.7'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.6'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.6'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.5'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.5'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.4'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.4'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.3'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.3'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject jsConstructor
WARNING: Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.2'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[Automation server can't create object for 'ShockwaveFlash.ShockwaveFlash.2'.] sourceName=[http://baike.bdimg.com/static/common/pkg/framework_2fdf7f19.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[The data necessary to complete this operation is not yet available.] sourceName=[http://baike.bdimg.com/static/common/ui/jquery/jquery_ba31c430.js] line=[15] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[An invalid or illegal selector was specified (selector: ':checked' error: Invalid selector: *:checked).] sourceName=[http://baike.bdimg.com/static/common/ui/jquery/jquery_ba31c430.js] line=[22] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter runtimeError
SEVERE: runtimeError: message=[An invalid or illegal selector was specified (selector: ':enabled' error: Invalid selector: *:enabled).] sourceName=[http://baike.bdimg.com/static/common/ui/jquery/jquery_ba31c430.js] line=[22] lineSource=[null] lineOffset=[0]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
WARNING: Expected content type of 'application/javascript' or 'application/ecmascript' for remotely loaded JavaScript element at 'http://a.baidu.com/ecom?di=216,790&tm=baiduASPT216S,baiduASPT790S&tn=baidubaike_pg,baidubaike_pg&word=%CA%A9%BB%AA%CE%C4&asp_url=file%3A%2F%2F%2Fhome%2Fm00nlight%2FDocuments%2Fdata%2Fbaike_raw%2Fbaike%2F000%2F1554000.htm%3Flemmaid%3D2024516', but got 'text/html'.
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.WebClient printContentIfNecessary
INFO: statusCode=[404] contentType=[text/html]
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.WebClient printContentIfNecessary
INFO: File: /viewpagebanner/baikeDynamicData.js
Nov 25, 2014 10:17:02 AM com.gargoylesoftware.htmlunit.html.HtmlPage loadExternalJavaScriptFile
SEVERE: Error loading JavaScript from [file:/viewpagebanner/baikeDynamicData.js?b=undefined&random=0.4433491969309997].
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for file:/viewpagebanner/baikeDynamicData.js?b=undefined&random=0.4433491969309997
        at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:496)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1100)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1039)
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
        at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:729)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.access$500(JavaScriptEngine.java:92)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:679)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:616)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setState(XMLHttpRequest.java:230)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setOnreadystatechange(XMLHttpRequest.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:120)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject$GetterSlot.setValue(ScriptableObject.java:295)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.putImpl(ScriptableObject.java:2796)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.put(ScriptableObject.java:521)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.put(XMLHttpRequest.java:890)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.putProperty(ScriptableObject.java:2479)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1569)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1564)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1253)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3031)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:561)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:669)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1062)
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
        at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:729)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.access$500(JavaScriptEngine.java:92)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:679)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:602)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:507)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:570)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:545)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptIfPossible(HtmlPage.java:959)
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded(HtmlScript.java:347)
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:425)
        at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:266)
        at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:286)
        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:683)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:642)
        at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
        at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
        at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
        at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
        at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3116)
        at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2083)
        at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:918)
        at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
        at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:899)
        at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:242)
        at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:188)
        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
        at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:437)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
        at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:361)
        at yokogiri.core$get_page.invoke(core.clj:163)
        at yokogiri.core$as_page.invoke(core.clj:174)
        at yokogiri.core$as_page.invoke(core.clj:173)
        at com.sixestates.baike$extract_one_page.invoke(baike.clj:35)
        at com.sixestates.baike$eval3605.invoke(form-init6545478542582415201.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6666)
        at clojure.core$eval.invoke(core.clj:2927)
        at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
        at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
        at clojure.main$repl$fn__6634.invoke(main.clj:257)
        at clojure.main$repl.doInvoke(main.clj:257)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__589.invoke(interruptible_eval.clj:56)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:41)
        at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__630$fn__633.invoke(interruptible_eval.clj:171)
        at clojure.core$comp$fn__4192.invoke(core.clj:2402)
        at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__623.invoke(interruptible_eval.clj:138)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)


FailingHttpStatusCodeException 404 Not Found for file:/viewpagebanner/baikeDynamicData.js?b=undefined&random=0.4433491969309997  com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary (WebClient.java:496)
```

It seems there is some javascript loading error. But the `nokogiri` does not need to load the javascript library to do the parse of the html page.

Github does not support html attachment, the test html source file can be found at:
http://pastebin.com/rs9CVNtv

**Comment by devn** [comment]
You could try disabling js?

**Comment by m00nlight** [comment]
How to? It seems there is no option in yokogiri for doing this, right? Should diable js in htmlunit?

**Comment by devn** [comment]
See: https://github.com/devn/yokogiri/blob/master/src/yokogiri/core.clj#L115

**Comment by devn** [comment]
@m00nlight Did this work for you?
