### ISSUE TITLE
NoClassDefFoundError: org/w3c/dom/ElementTraversal

### ISSUE THREAD

**Issue by ghost** [devn/yokogiri#7]
On a `lein run` getting:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal, compiling:(yokogiri/core.clj:12:23)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6894)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.analyze(Compiler.java:6649)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6025)
    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5401)
    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3975)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6885)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.access$300(Compiler.java:38)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:593)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
    at clojure.lang.Compiler.analyze(Compiler.java:6688)
    at clojure.lang.Compiler.analyze(Compiler.java:6649)
    at clojure.lang.Compiler.eval(Compiler.java:6950)
    at clojure.lang.Compiler.load(Compiler.java:7393)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5445.invoke(core.clj:5871)
    at clojure.core$load.invokeStatic(core.clj:5870)
    at clojure.core$load_one.invokeStatic(core.clj:5671)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
    at clojure.core$load_lib.invokeStatic(core.clj:5715)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$load_libs.invokeStatic(core.clj:5753)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$require.invokeStatic(core.clj:5775)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojureme.models.scraper$eval8360$loading__5337__auto____8361.invoke(scraper.clj:1)
    at clojureme.models.scraper$eval8360.invokeStatic(scraper.clj:1)
    at clojureme.models.scraper$eval8360.invoke(scraper.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6946)
    at clojure.lang.Compiler.eval(Compiler.java:6935)
    at clojure.lang.Compiler.load(Compiler.java:7393)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5445.invoke(core.clj:5871)
    at clojure.core$load.invokeStatic(core.clj:5870)
    at clojure.core$load_one.invokeStatic(core.clj:5671)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
    at clojure.core$load_lib.invokeStatic(core.clj:5715)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$load_libs.invokeStatic(core.clj:5757)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$require.invokeStatic(core.clj:5775)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojureme.controllers.scraper$eval8354$loading__5337__auto____8355.invoke(scraper.clj:1)
    at clojureme.controllers.scraper$eval8354.invokeStatic(scraper.clj:1)
    at clojureme.controllers.scraper$eval8354.invoke(scraper.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6946)
    at clojure.lang.Compiler.eval(Compiler.java:6935)
    at clojure.lang.Compiler.load(Compiler.java:7393)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5445.invoke(core.clj:5871)
    at clojure.core$load.invokeStatic(core.clj:5870)
    at clojure.core$load_one.invokeStatic(core.clj:5671)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
    at clojure.core$load_lib.invokeStatic(core.clj:5715)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$load_libs.invokeStatic(core.clj:5757)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$require.invokeStatic(core.clj:5775)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojureme.server$eval3397$loading__5337__auto____3398.invoke(server.clj:1)
    at clojureme.server$eval3397.invokeStatic(server.clj:1)
    at clojureme.server$eval3397.invoke(server.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6946)
    at clojure.lang.Compiler.eval(Compiler.java:6935)
    at clojure.lang.Compiler.load(Compiler.java:7393)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.loadResourceScript(RT.java:363)
    at clojure.lang.RT.load(RT.java:453)
    at clojure.lang.RT.load(RT.java:419)
    at clojure.core$load$fn__5445.invoke(core.clj:5871)
    at clojure.core$load.invokeStatic(core.clj:5870)
    at clojure.core$load_one.invokeStatic(core.clj:5671)
    at clojure.core$load_one.invoke(core.clj)
    at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
    at clojure.core$load_lib.invokeStatic(core.clj:5715)
    at clojure.core$load_lib.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$load_libs.invokeStatic(core.clj:5753)
    at clojure.core$load_libs.doInvoke(core.clj)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:635)
    at clojure.core$require.invokeStatic(core.clj:5775)
    at clojure.core$require.doInvoke(core.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at user$eval5.invokeStatic(form-init589888798738320790.clj:1)
    at user$eval5.invoke(form-init589888798738320790.clj)
    at clojure.lang.Compiler.eval(Compiler.java:6946)
    at clojure.lang.Compiler.eval(Compiler.java:6935)
    at clojure.lang.Compiler.load(Compiler.java:7393)
    at clojure.lang.Compiler.loadFile(Compiler.java:7331)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
    at java.lang.Class.privateGetPublicMethods(Class.java:2814)
    at java.lang.Class.getMethods(Class.java:1602)
    at clojure.lang.Reflector.getMethods(Reflector.java:373)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:990)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
    ... 135 more
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 178 more
Subprocess failed
```

**Comment by ghost** [comment]
Resolved itself -- gremlins

**Comment by ghost** [comment]
Discovered the culprit

in the `project.clj` file, when `[com.cemerick/friend "0.2.1”]` is put before `[yokogiri "1.5.8”]` under `:dependencies`, it throws the error above.

**Comment by ghost** [comment]
Update: Having both friend and yokogiri, no matter the order in dependencies is breaking a few tests.
